### PR TITLE
Resolves #657

### LINKED ISSUE #657: nullpointer exception in CamelIdeaUtils.findEndpointDeclarations
plugin 0.8.2 / IDEA 2021.3.1 

```
In file: file://......../route/MainRouteBuilder.java

java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.cameltooling.idea.util.CamelIdeaUtils.findEndpointDeclarations(CamelIdeaUtils.java:252)
	at com.github.cameltooling.idea.util.CamelIdeaUtils.findEndpointDeclarations(CamelIdeaUtils.java:245)
	at com.github.cameltooling.idea.reference.endpoint.direct.DirectEndpointReference.lambda$multiResolve$0(DirectEndpointReference.java:51)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.github.cameltooling.idea.reference.endpoint.direct.DirectEndpointReference.multiResolve(DirectEndpointReference.java:51)
	at com.github.cameltooling.idea.annotator.CamelEndpointAnnotator.lambda$validateEndpointReference$2(CamelEndpointAnnotator.java:126)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.github.cameltooling.idea.annotator.CamelEndpointAnnotator.validateEndpointReference(CamelEndpointAnnotator.java:125)
	at com.github.cameltooling.idea.annotator.CamelEndpointAnnotator.validateText(CamelEndpointAnnotator.java:93)
	at com.github.cameltooling.idea.annotator.AbstractCamelAnnotator.annotate(AbstractCamelAnnotator.java:56)
	at com.github.cameltooling.idea.annotator.CamelEndpointAnnotator.annotate(CamelEndpointAnnotator.java:46)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:344)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### PR DESCRIPTION
**Pull request by javaduke**
Resolves #657

### CODE REVIEW

File: camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/YamlCamelIdeaUtils.java [hunk 1]
```diff
@@ -146,12 +147,12 @@ public PsiElement getPsiElementForCamelBeanMethod(PsiElement element) {
 
     @Override
     public List<PsiElement> findEndpointUsages(Module module, Predicate<String> uriCondition) {
-        return null;
+        return new ArrayList<>();
```
Comment (davsclaus) [inline camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/YamlCamelIdeaUtils.java:150]: You can likely use Collections.EMPTY_LIST() instead

Comment (javaduke) [reply camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/YamlCamelIdeaUtils.java:150]: Ah, right, I was thinking about this, but for some reason didn't do it, let me make this change. This is all just temporary, until the full YAML support is done.
